// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('simple_substraction', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('simple_substraction', async function() {
    await driver.get("http://127.0.0.1:5500/src/index.html")
    await driver.manage().window().setRect({ width: 976, height: 691 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("4")
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("1")
    await driver.findElement(By.css(".button-group > button:nth-child(2)")).click()
    assert(await driver.findElement(By.id("result")).getText() == "Result: 3")
  })
})
